image: gcc
before_script:
  - apt-get update --yes
  - apt-get install --yes cmake
  - apt-get install --yes libgtest-dev
  - apt-get install --yes cppcheck

stages:
  - lib_sort
  - bubblesort_lib
  - tests
  - tests2
  - prog
  -progb

tests:
  stage: test
  script:
    - ./linters/run.sh

tests2:
  stage: tests2
  script:
    - mkdir sort
    - cd sort
    - cmake .
  artifacts:
    paths:
      - "tests2"

tests:
  stage: tests
  script:
    - cd build
    - ./tests

tests:
  script:
    - apt-get update && apt-get install -y valgrind
    - cd build
    - valgrind --tool=memcheck ./tests
    - valgrind --tool=memcheck ./tests2
    - valgrind --tool=memcheck ./prog
    - valgrind --tool=memcheck ./progb

  when: manual
  allow_failure: false

