# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /usr/technopark/iz2/sort

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /usr/technopark/iz2/sort

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /usr/technopark/iz2/sort/CMakeFiles /usr/technopark/iz2/sort/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /usr/technopark/iz2/sort/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named tests2

# Build rule for target.
tests2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tests2
.PHONY : tests2

# fast build rule for target.
tests2/fast:
	$(MAKE) -f CMakeFiles/tests2.dir/build.make CMakeFiles/tests2.dir/build
.PHONY : tests2/fast

#=============================================================================
# Target rules for targets named tests

# Build rule for target.
tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tests
.PHONY : tests

# fast build rule for target.
tests/fast:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/build
.PHONY : tests/fast

#=============================================================================
# Target rules for targets named progb

# Build rule for target.
progb: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 progb
.PHONY : progb

# fast build rule for target.
progb/fast:
	$(MAKE) -f CMakeFiles/progb.dir/build.make CMakeFiles/progb.dir/build
.PHONY : progb/fast

#=============================================================================
# Target rules for targets named bubblesort_lib

# Build rule for target.
bubblesort_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bubblesort_lib
.PHONY : bubblesort_lib

# fast build rule for target.
bubblesort_lib/fast:
	$(MAKE) -f CMakeFiles/bubblesort_lib.dir/build.make CMakeFiles/bubblesort_lib.dir/build
.PHONY : bubblesort_lib/fast

#=============================================================================
# Target rules for targets named prog

# Build rule for target.
prog: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 prog
.PHONY : prog

# fast build rule for target.
prog/fast:
	$(MAKE) -f CMakeFiles/prog.dir/build.make CMakeFiles/prog.dir/build
.PHONY : prog/fast

#=============================================================================
# Target rules for targets named lib_sort

# Build rule for target.
lib_sort: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lib_sort
.PHONY : lib_sort

# fast build rule for target.
lib_sort/fast:
	$(MAKE) -f CMakeFiles/lib_sort.dir/build.make CMakeFiles/lib_sort.dir/build
.PHONY : lib_sort/fast

bubblesort.o: bubblesort.cpp.o

.PHONY : bubblesort.o

# target to build an object file
bubblesort.cpp.o:
	$(MAKE) -f CMakeFiles/bubblesort_lib.dir/build.make CMakeFiles/bubblesort_lib.dir/bubblesort.cpp.o
.PHONY : bubblesort.cpp.o

bubblesort.i: bubblesort.cpp.i

.PHONY : bubblesort.i

# target to preprocess a source file
bubblesort.cpp.i:
	$(MAKE) -f CMakeFiles/bubblesort_lib.dir/build.make CMakeFiles/bubblesort_lib.dir/bubblesort.cpp.i
.PHONY : bubblesort.cpp.i

bubblesort.s: bubblesort.cpp.s

.PHONY : bubblesort.s

# target to generate assembly for a file
bubblesort.cpp.s:
	$(MAKE) -f CMakeFiles/bubblesort_lib.dir/build.make CMakeFiles/bubblesort_lib.dir/bubblesort.cpp.s
.PHONY : bubblesort.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/prog.dir/build.make CMakeFiles/prog.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/prog.dir/build.make CMakeFiles/prog.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/prog.dir/build.make CMakeFiles/prog.dir/main.cpp.s
.PHONY : main.cpp.s

mainb.o: mainb.cpp.o

.PHONY : mainb.o

# target to build an object file
mainb.cpp.o:
	$(MAKE) -f CMakeFiles/progb.dir/build.make CMakeFiles/progb.dir/mainb.cpp.o
.PHONY : mainb.cpp.o

mainb.i: mainb.cpp.i

.PHONY : mainb.i

# target to preprocess a source file
mainb.cpp.i:
	$(MAKE) -f CMakeFiles/progb.dir/build.make CMakeFiles/progb.dir/mainb.cpp.i
.PHONY : mainb.cpp.i

mainb.s: mainb.cpp.s

.PHONY : mainb.s

# target to generate assembly for a file
mainb.cpp.s:
	$(MAKE) -f CMakeFiles/progb.dir/build.make CMakeFiles/progb.dir/mainb.cpp.s
.PHONY : mainb.cpp.s

sort.o: sort.cpp.o

.PHONY : sort.o

# target to build an object file
sort.cpp.o:
	$(MAKE) -f CMakeFiles/bubblesort_lib.dir/build.make CMakeFiles/bubblesort_lib.dir/sort.cpp.o
	$(MAKE) -f CMakeFiles/lib_sort.dir/build.make CMakeFiles/lib_sort.dir/sort.cpp.o
.PHONY : sort.cpp.o

sort.i: sort.cpp.i

.PHONY : sort.i

# target to preprocess a source file
sort.cpp.i:
	$(MAKE) -f CMakeFiles/bubblesort_lib.dir/build.make CMakeFiles/bubblesort_lib.dir/sort.cpp.i
	$(MAKE) -f CMakeFiles/lib_sort.dir/build.make CMakeFiles/lib_sort.dir/sort.cpp.i
.PHONY : sort.cpp.i

sort.s: sort.cpp.s

.PHONY : sort.s

# target to generate assembly for a file
sort.cpp.s:
	$(MAKE) -f CMakeFiles/bubblesort_lib.dir/build.make CMakeFiles/bubblesort_lib.dir/sort.cpp.s
	$(MAKE) -f CMakeFiles/lib_sort.dir/build.make CMakeFiles/lib_sort.dir/sort.cpp.s
.PHONY : sort.cpp.s

tests.o: tests.cpp.o

.PHONY : tests.o

# target to build an object file
tests.cpp.o:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests.cpp.o
.PHONY : tests.cpp.o

tests.i: tests.cpp.i

.PHONY : tests.i

# target to preprocess a source file
tests.cpp.i:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests.cpp.i
.PHONY : tests.cpp.i

tests.s: tests.cpp.s

.PHONY : tests.s

# target to generate assembly for a file
tests.cpp.s:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests.cpp.s
.PHONY : tests.cpp.s

tests2.o: tests2.cpp.o

.PHONY : tests2.o

# target to build an object file
tests2.cpp.o:
	$(MAKE) -f CMakeFiles/tests2.dir/build.make CMakeFiles/tests2.dir/tests2.cpp.o
.PHONY : tests2.cpp.o

tests2.i: tests2.cpp.i

.PHONY : tests2.i

# target to preprocess a source file
tests2.cpp.i:
	$(MAKE) -f CMakeFiles/tests2.dir/build.make CMakeFiles/tests2.dir/tests2.cpp.i
.PHONY : tests2.cpp.i

tests2.s: tests2.cpp.s

.PHONY : tests2.s

# target to generate assembly for a file
tests2.cpp.s:
	$(MAKE) -f CMakeFiles/tests2.dir/build.make CMakeFiles/tests2.dir/tests2.cpp.s
.PHONY : tests2.cpp.s

thread.o: thread.cpp.o

.PHONY : thread.o

# target to build an object file
thread.cpp.o:
	$(MAKE) -f CMakeFiles/lib_sort.dir/build.make CMakeFiles/lib_sort.dir/thread.cpp.o
.PHONY : thread.cpp.o

thread.i: thread.cpp.i

.PHONY : thread.i

# target to preprocess a source file
thread.cpp.i:
	$(MAKE) -f CMakeFiles/lib_sort.dir/build.make CMakeFiles/lib_sort.dir/thread.cpp.i
.PHONY : thread.cpp.i

thread.s: thread.cpp.s

.PHONY : thread.s

# target to generate assembly for a file
thread.cpp.s:
	$(MAKE) -f CMakeFiles/lib_sort.dir/build.make CMakeFiles/lib_sort.dir/thread.cpp.s
.PHONY : thread.cpp.s

threadfb.o: threadfb.cpp.o

.PHONY : threadfb.o

# target to build an object file
threadfb.cpp.o:
	$(MAKE) -f CMakeFiles/bubblesort_lib.dir/build.make CMakeFiles/bubblesort_lib.dir/threadfb.cpp.o
.PHONY : threadfb.cpp.o

threadfb.i: threadfb.cpp.i

.PHONY : threadfb.i

# target to preprocess a source file
threadfb.cpp.i:
	$(MAKE) -f CMakeFiles/bubblesort_lib.dir/build.make CMakeFiles/bubblesort_lib.dir/threadfb.cpp.i
.PHONY : threadfb.cpp.i

threadfb.s: threadfb.cpp.s

.PHONY : threadfb.s

# target to generate assembly for a file
threadfb.cpp.s:
	$(MAKE) -f CMakeFiles/bubblesort_lib.dir/build.make CMakeFiles/bubblesort_lib.dir/threadfb.cpp.s
.PHONY : threadfb.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... tests2"
	@echo "... tests"
	@echo "... progb"
	@echo "... rebuild_cache"
	@echo "... bubblesort_lib"
	@echo "... prog"
	@echo "... edit_cache"
	@echo "... lib_sort"
	@echo "... bubblesort.o"
	@echo "... bubblesort.i"
	@echo "... bubblesort.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... mainb.o"
	@echo "... mainb.i"
	@echo "... mainb.s"
	@echo "... sort.o"
	@echo "... sort.i"
	@echo "... sort.s"
	@echo "... tests.o"
	@echo "... tests.i"
	@echo "... tests.s"
	@echo "... tests2.o"
	@echo "... tests2.i"
	@echo "... tests2.s"
	@echo "... thread.o"
	@echo "... thread.i"
	@echo "... thread.s"
	@echo "... threadfb.o"
	@echo "... threadfb.i"
	@echo "... threadfb.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

